version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    reviewers:
      - "RobertoGraham"
  - package-ecosystem: "terraform"
    directory: "/terraform/mutual-tls"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    reviewers:
      - "RobertoGraham"
