name: Compile and Upload Native Binaries

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/main.yaml
      - gradle/**
      - src/**
      - terraform/**
      - gradlew
      - build.gradle.kts
      - setting.gradle.kts

jobs:
  publish:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: liberica
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: true
      - uses: gradle/actions/wrapper-validation@v3
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew test
      - run: ./gradlew nativeCompile
      - run: printf "TF_CLI_CONFIG_FILE=%s" "${{ github.workspace }}${{ runner.os == 'Windows' && '\' || '/' }}terraform.tfrc" >> "$GITHUB_ENV"
      - run: >-
          touch "$TF_CLI_CONFIG_FILE"
          &&
          printf 'provider_installation{dev_overrides{"robertograham.github.io/tpp4j/test"="%s"}${{ runner.os == 'Windows' && '\r\n' || '\n' }}direct{}}' "${{ github.workspace }}${{ runner.os == 'Windows' && '\' || '/' }}build${{ runner.os == 'Windows' && '\' || '/' }}native${{ runner.os == 'Windows' && '\' || '/' }}nativeCompile" | sed 's~\\~\\\\~g' >> "$TF_CLI_CONFIG_FILE"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
      - run: terraform plan
        working-directory: terraform/tpp4j-test
        env:
          TF_LOG: trace
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.6.2"
      - run: tofu plan
        working-directory: terraform/tpp4j-test
        env:
          TF_LOG: trace
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-test_${{ matrix.os }}
          path: build/native/nativeCompile/terraform-provider-test*
